dist: trusty
language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - .composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install -n

script:
  - phpunit --coverage-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)