name: Docs Publish

on:
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Phive
        uses: szepeviktor/phive-install@v1

      - name: Install phpDocumentor
        run: phive install phpDocumentor

      - name: Generate Docs
        run: phpDocumentor

      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: docs